### ISSUE TITLE
Package `jupyter-notebook` should receive the broken badge

### ISSUE THREAD

**Issue by confused-Techie** [pulsar-edit/package-backend#159]
Fails to install [source](https://discord.com/channels/992103415163396136/992103415163396139/1098780467072860170)

**Comment by confused-Techie** [comment]
Additionally, package `omnisharp-atom` should receive the broken badge

**Comment by Daeraxa** [comment]
> Additionally, package `omnisharp-atom` should receive the broken badge

For reference: https://github.com/orgs/pulsar-edit/discussions/197, https://github.com/OmniSharp/omnisharp-atom/issues/1037

Seems to be unsupported by the maintainer (last update 6 years ago) but it seems there could be a valid workaround if somebody wanted to maintain a fork.

**Comment by goyalyashpal** [comment]
> install [source](https://discord.com/channels/992103415163396136/992103415163396139/1098780467072860170)

source is discord requiring login - aka no public view. cn u summarise? thnx (:

**Comment by confused-Techie** [comment]
> > install [source](https://discord.com/channels/992103415163396136/992103415163396139/1098780467072860170)
> 
> source is discord requiring login - aka no public view. cn u summarise? thnx (:

I'll provide a transcription:

> 6lackcraft: BTW, just got an error on my jupyter notebook installation
![image](https://github.com/pulsar-edit/package-backend/assets/26921489/2655b144-ef6a-40e3-b7c2-fdf03a43e726)
> 6lackcraft: kinda weird, but my jupyter notebook plugin didn't build right apparently
>
> confused-Techie: It wasn't so much not built correctly, looks like Pulsar is complaining about the JavaScript source itself.
> One thing to keep in mind is that with our upgrades to Electron/NodeJS Sloppy mode javascript is no longer allowed, meaning packages that use it will break.
> But I can't find evidence of that within the `jupyter-notebook` package. So I'm trying to see what's going on there.
>
> 6lackcraft: Thanks so much for taking the time to review that!
> Let me know how I can help.
> Is the error message indicative of a type in the source code?
> Failed to load the jupyter-notebook package
```javascript
/home/mortal_engine/.pulsar/packages/jupyter-notebook/lib/main.js: Unexpected token, expected "," (36:4)
  34 |         return el;
  35 |       }
> 36 |     });
     |     ^
  37 |   },
  38 |
  39 |   deactivate() {
```
>
> savetheclocktower: there's some JSX just above that line. i wonder if that's the problem
> because there's nothing wrong with the code at that position that i can tell
> well, this isn't a good sign: https://github.com/jupyter/atom-notebook/issues
>
> 6lackcraft: LOLOL!
