### ISSUE TITLE
Package `atom-oss-license` should receive Archived badge

### ISSUE THREAD

**Issue by confused-Techie** [pulsar-edit/package-backend#173]
This also would mean we create the archived badge.

It should receive the `type` of `info` since a package being archived alone does not mean it contains any issues, but very well mean that the package is broken, and will not receive any support or updates.

Ideally this can be  a helpful way at a glance to see a package that's under active maintenance. 

Additionally, I think there is some merit in a conversation about if we should remove archived package that are also broken, since there is no way they will every be resolved. 

But as for what this issue is originally about:

* [package](https://web.pulsar-edit.dev/packages/atom-oss-license)
* [repo](https://github.com/mmk2410/atom-oss-license)

**Comment by confused-Techie** [comment]
@Daeraxa that's totally fair.
If we wanted to consider hiding them, we could do what happens when NPM delists a package. Essentially it doesn't show up on search at all, but can still be navigated to directly. Since to hide things via a special flag would require building a system to do so, but delisting things is as easy as setting no versions to the latest. This will also break updating the package, but if it's broken and archived, it won't really be getting updates anymore.

Which the bonus of just delisting the package is if a new version is published it'll automatically be de-delisted, so it'll show up on search again (As well as of course having the broken badge removed)

**Comment by Daeraxa** [comment]
> Since to hide things via a special flag would require building a system to do so

Is this not something we want anyway? Like being able to filter by `made for pulsar` or remove `deprecated` from search?

**Comment by confused-Techie** [comment]
You do have a good point there, where showing items based on data is something we want.
I was referring more to removing items based on data. It's still totally possible, and honestly the more I thought about it, this doesn't have to be part of the data gathering step (ie hitting the DB) but instead it'd be trivial to implement as a data presentation step (ie constructing a package object short/full). If done that way there's more potential for performance issues, but it'd be the simplest way to implement this as soon as possible, so has some merit.
