### ISSUE TITLE
Remove appcelerator-titanium pacakge

### ISSUE THREAD

**Issue by ewanharris** [pulsar-edit/package-backend#190]
👋🏻 

Would it be possible to remove the [appcelerator-titanium](https://web.pulsar-edit.dev/packages/appcelerator-titanium) package as it has now been replaced by the [titanium](https://web.pulsar-edit.dev/packages/titanium) package.

I've attempted to remove this via the unpublish command but receive an error when attempting that.

**Comment by confused-Techie** [comment]
@ewanharris I would be much more than happy to help you in removing this, although you should be able to do so via the unpublish command. Would you mind sharing what the error was, and when about you attempted to do so?

**Comment by confused-Techie** [comment]
@ewanharris If you wouldn't mind, as an agnostic, and forge universal method to verify that you in fact have the correct permissions to initiate a deletion of the package from Pulsar, would you mind creating a branch on [`tidev/pulsar-titanium`](https://github.com/tidev/pulsar-titanium) named "i-consent-to-ppr-deletion".

Doing so will let us easily ensure that you have the correct permissions, and this decision is in line with other maintainers for that repository. And can then be deleted after the fact with little to no effect on the rest of the repository.

I'd also like to ensure that you are aware that deleting a package from the Pulsar Package Registry (PPR) means:

* Download count of the repository will be lost
* Star count of the repository will be lost (both Atom stars, and Pulsar stars)
* All metadata of the package will be permanently and irrevocably removed from the PPR with **NO** method of recovery
* All versions of the previous package metadata will also be totally removed
* The name of the package will never be available for publish again, to avoid exposing users to supply chain attacks

---

If this all sounds good, feel free to create the branch as discussed above, and I will get to deletion as soon as possible. But please allow for about 5 days for deletion to occur. (This is a totally manual process, so I apologize for long turn around times)

**Comment by ewanharris** [comment]
@confused-Techie, sure! The error I got was the below, 
```
pulsar -p unpublish appcelerator-titanium
Are you sure you want to unpublish ALL VERSIONS of 'appcelerator-titanium'? This will remove it from the ppm registry, including download counts and stars, and this action is irreversible. (no)yes
Unpublishing appcelerator-titanium ✗
Unpublishing failed: Application Error
```

As for deletion, the other TiDev members are in agreement (see the issue [here](https://github.com/tidev/pulsar-titanium/issues/654)), we had attempted to rename the `appcelerator-titanium` package initially but that hit some issues and that's why we now have the separate titanium package. If it's still possible to somehow merge/rename the [appcelerator-titanium](https://web.pulsar-edit.dev/packages/appcelerator-titanium) package into [titanium](https://web.pulsar-edit.dev/packages/titanium) then that would be preferable, but if not then we're good with the deletion.

I've created the branch [here](https://github.com/tidev/pulsar-titanium/tree/i-consent-to-ppr-deletion),

**Comment by confused-Techie** [comment]
@ewanharris I'll have to investigate what's gone wrong with your attempt to unpublish the package, sorry about that being troublesome.

As for merging the package, I can absolutely merge the star count, or at least the Atom star count, and the download count can be easily moved over, so I'd be happy to do so, if that sounds alright.

I'll investigate into transferring the versions too, as theoretically it should be simple, but is something I have never attempted before. 

But if that does sound like a good plan to you, then let me know and I'll see what all I can transfer under the new name

**Comment by confused-Techie** [comment]
A quick addition to this, unfortunately I'm unable to determine what exactly caused the unpublish to fail. Seems this section of the codebase has not received the same love in trace logging as other areas (such as publishing receiving the most updates in this area), so I'll work on adding more testing and logging here to see if I can later on determine where it has gone wrong. But thanks for providing that logging output!

**Comment by confused-Techie** [comment]
@ewanharris Feel free to delete that branch I had you create, I've finished transferring the download count, and stars count between the packages, and deleting the old `appcelerator-titanium` package.

Thanks a ton for working with me on that one.

**Comment by m1ga** [comment]
Thanks @confused-Techie :+1:

**Comment by ewanharris** [comment]
Thank you so much for handling that @confused-Techie!
