### ISSUE TITLE
Mark as outdated `autocomplete-paths` package

### ISSUE THREAD

**Issue by AlexWayfer** [pulsar-edit/package-backend#194]
**Is this feature Currently Implemented in any way with the upstream API Server**
- [x] Yes
- [ ] No

**Is your feature request related to a problem? Please describe.**

I was suffering from this problem for a long time. I thought it's a problem with some core autocomplete package, but safe mode and disabling packages one-by-one helped me to figure out the reason.

https://web.pulsar-edit.dev/packages/autocomplete-paths

Steps to reproduce:
* Write `attr` in a Ruby file.
* Select some autocompletion, like `attr_reader`.
* Press `Tab` to autocomplete.
* Get nothing, still `attr`.

It works for the second time for some reason.

[Screencast from 2023-08-17 15-54-02.webm](https://github.com/pulsar-edit/package-backend/assets/6510020/2be4449e-3b6e-416d-b6fd-77cd8bd28071)

**Describe the solution you'd like**

Please, mark this package as an outdated, or broken, or dangerous — I'm not sure.

~~I haven't found any related issues in [the original package repository](https://github.com/atom-community/autocomplete-paths), but also it seems outdated and I don't know how to fill it.~~

I've created an issue for the package: https://github.com/atom-community/autocomplete-paths/issues/287

**Comment by savetheclocktower** [comment]
This is strange.

Can you try the following steps for me?

1. Open your developer tools (<kbd>Ctrl-Shift-I</kbd>, or View -> Developer -> Toggle Developer Tools)
2. Focus the “Console” tab
3. Run the following snippet:
    ```js
    copy(JSON.stringify(atom.config.get('autocomplete-plus'), null, 2))
    ````
4. Paste the output into a comment within a fenced code block (three backticks above and below)

One thing I'm curious about is whether this behavior is different when you _click_ on the choice you want instead of pressing <kbd>Tab</kbd>.

**Comment by AlexWayfer** [comment]
```json
{
  "confirmCompletion": "tab",
  "defaultProvider": "Symbol",
  "minimumWordLength": 2,
  "enableAutoActivation": true,
  "autoActivationDelay": 0,
  "maxVisibleSuggestions": 10,
  "useCoreMovementCommands": true,
  "fileBlacklist": [
    ".*"
  ],
  "scopeBlacklist": [],
  "includeCompletionsFromAllBuffers": true,
  "strictMatching": false,
  "extraWordCharacters": "",
  "enableBuiltinProvider": true,
  "builtinProviderBlacklist": ".source.gfm",
  "backspaceTriggersAutocomplete": false,
  "enableAutoConfirmSingleSuggestion": true,
  "suggestionListFollows": "Word",
  "suppressActivationForEditorClasses": [
    "vim-mode.command-mode",
    "vim-mode.visual-mode",
    "vim-mode.operator-pending-mode"
  ],
  "consumeSuffix": true,
  "useAlternateScoring": true,
  "useLocalityBonus": true,
  "enableExtendedUnicodeSupport": false,
  "similarSuggestionRemoval": "none",
  "moveToCancel": false
}
```

**Comment by savetheclocktower** [comment]
OK, two more things to try — let me know how each one works:

1. When the completions first appear, and `attr_reader` is visible, use your mouse/trackpad to click on it. See if that works.
2. Change your “Keymap for Confirming a Suggestion” setting (in the `autocomplete-plus` settings) to either “enter” or “tab and enter.” Then try it again and use the <kbd>Enter</kbd> key to try to choose `attr_reader`.

These results will help us diagnose the problem. Right now I'm a bit perplexed how the presence or absence of a particular autocomplete provider could cause the symptoms you're describing, but I believe you that it's happening.

**Comment by AlexWayfer** [comment]
> 2\. Change your “Keymap for Confirming a Suggestion” setting (in the autocomplete-plus settings) to either “enter” or “tab and enter.” Then try it again and use the Enter key to try to choose attr_reader.

I was trying this before posting, doesn't help.



> * When the completions first appear, and attr_reader is visible, use your mouse/trackpad to click on it. See if that works.

Mouse always works.

---

I was facing this annoying issue again, even after `autocomplete-path` disabling. It seemed more rarely, but finally I've got the reproducing actions:

* Type `attr`, gem autocompletion list.
* Select something, get completing or not (read below how it depends)
  * If not — delete some chars and try again — you will get it now.
* Now if you will select the whole line via `Home` key, for example, retry autocompletion — it'll work.
* **But**, if you will press `Enter` (not when autocompletion list is showed) to go to a new line — you (or just I) will guaranteed get this bug, not-completing.

So, it breaks after `Enter` for a new line. Somehow. It doesn't depends on `autocomplete-path` package. Thank you for your help in investigation. I should move somewhere this issue, but now I'm not sure where exactly: `autocomplete-plus` package?

Video: 
[Screencast from 2023-08-18 12-58-41.webm](https://github.com/pulsar-edit/package-backend/assets/6510020/1ea9a842-2366-404e-ba53-093f792e5ad0)
