### ISSUE TITLE
Archive deep-purple-syntax theme

### ISSUE THREAD

**Issue by Daeraxa** [pulsar-edit/package-backend#209]
https://web.pulsar-edit.dev/packages/deep-purple-syntax should be archived as the repo has been deleted - https://github.com/nickvanderwildt/deep-purple-syntax

See: https://discord.com/channels/992103415163396136/992105429591134330/1184523458974076948

**Comment by confused-Techie** [comment]
Thanks a ton for reporting this, I'll get on it as soon as I can
