### ISSUE TITLE
Archive Facebook Nuclide packages

### ISSUE THREAD

**Issue by Daeraxa** [pulsar-edit/package-backend#245]
There are a number of packages published as part of Nuclide which are marked as archived on GitHub under the "facebookarchive" org.

They all seem to be published as "NEEDS OWNER" now as an easy way to find more.

Examples:
https://web.pulsar-edit.dev/packages/atom-ide-debugger-node
https://web.pulsar-edit.dev/packages/atom-ide-debugger-python
https://web.pulsar-edit.dev/packages/atom-ide-debugger-native-gdb
https://web.pulsar-edit.dev/packages/atom-ide-debugger-react-native
https://web.pulsar-edit.dev/packages/atom-ide-debugger-ocaml

**Comment by confused-Techie** [comment]
Thanks for the issue and pointing this out. I'll get on it when I can
