### ISSUE TITLE
[BUG] Archive `autocomplete-javascript` package

### ISSUE THREAD

**Issue by AlexWayfer** [pulsar-edit/package-backend#248]
**What is the Bug**

Please, archive (and mark as broken?) [`autocomplete-javascript` package](https://web.pulsar-edit.dev/packages/autocomplete-javascript).

**How to Replicate the Bug**

It doesn't work. And there are issues about it without reactions:

https://github.com/guiguan/autocomplete-javascript/issues

![image](https://github.com/pulsar-edit/package-backend/assets/6510020/e801a4d1-6c30-4a27-8729-517cc91f1046)

**Comment by AlexWayfer** [comment]
And the most sad part of me it's not even occupying the name, but I've found no alternatives. So, I can even have autocomplete for Ruby, but not for JavaScript — insane.

**Comment by savetheclocktower** [comment]
`ide-typescript` (and my candidate for modernizing it, [`pulsar-ide-typescript-alpha`](https://web.pulsar-edit.dev/packages/pulsar-ide-typescript-alpha)) do a decent job at autocompleting JavaScript, despite the name. They do better at TypeScript (for obvious reasons), but you might be surprised at how well they analyze typeless JS.

**Comment by AlexWayfer** [comment]
> `ide-typescript` (and my candidate for modernizing it, [`pulsar-ide-typescript-alpha`](https://web.pulsar-edit.dev/packages/pulsar-ide-typescript-alpha)) do a decent job at autocompleting JavaScript, despite the name. They do better at TypeScript (for obvious reasons), but you might be surprised at how well they analyze typeless JS.

Thank you.

It seems conflicting (duplicating) some another package:

![image](https://github.com/pulsar-edit/package-backend/assets/6510020/30aac6f7-a569-448a-9de1-96bde8dc5ad7)

![image](https://github.com/pulsar-edit/package-backend/assets/6510020/b0039a87-cd68-43df-973f-52077bf9c2b4)

I don't know what I should to leave and what I should to turn off.

**Comment by savetheclocktower** [comment]
Perhaps post a list of your installed packages? It wouldn't be a built-in package. `pulsar -p list` or `ppm list` will list all your packages.
