### ISSUE TITLE
Archive tag for platformio packages

### ISSUE THREAD

**Issue by Daeraxa** [pulsar-edit/package-backend#261]
These all look to have been archived at the same time, 20/06/23
[platformio-ide](https://web.pulsar-edit.dev/packages/platformio-ide) - https://github.com/platformio/platformio-atom-ide
[platformio-ide-terminal](https://web.pulsar-edit.dev/packages/platformio-ide-terminal) - https://github.com/platformio/platformio-atom-ide-terminal
[platformio-ide-debugger](https://web.pulsar-edit.dev/packages/platformio-ide-debugger) - https://github.com/platformio/platformio-atom-ide-debugger

Weirdly [platformio-aia](https://web.pulsar-edit.dev/packages/platformio-aia) (https://github.com/platformio/platformio-aia) isn't archived...

**Comment by confused-Techie** [comment]
Thanks for the issue, I'm hoping to do a sweep of these requests this week

**Comment by confused-Techie** [comment]
This issue was resolved by #267
