### ISSUE TITLE
Releases missing from featured packages

### ISSUE THREAD

**Issue by jonian** [pulsar-edit/package-backend#3]
**Is this feature Currently Implemented in any way with the upstream API Server**
- [x] Yes
- [ ] No

**Is your feature request related to a problem? Please describe.**

Missing releases leads to featured packages not showing in settings view pulsar-edit/pulsar#137. As you can see [here](https://github.com/pulsar-edit/ppm/blob/master/src/featured.coffee#L40) it expects key `latest` in `releases`. Currently releases is an empty object.

**Comment by confused-Techie** [comment]
Since beta v0.1.0 has now been pushed to production, this issue is resolved. Feel free to read more on [Discord](https://discord.com/channels/992103415163396136/992231561724436591/1044759978931658832)
