### ISSUE TITLE
POST /api/packages/:packageName/versions - unused tag parameter

### ISSUE THREAD

**Issue by Digitalone1** [pulsar-edit/package-backend#34]
On the above-mentioned endpoint we specify a `tag` parameter. In the code it's described:

> A git tag for the version you'd like to create. It's important to note that the version name will not be taken from the tag, but from the `version` key in the `package.json` file at that ref.

Indeed we only consider the `version` inside the package json and the tag become unused. For this reason I commented it inside `package_handler.postPackagesVersion`. 

At the moment, a package can be published when a correct version is found inside the package json (retrieved from GH), even if the tag specified in the query is missing or it's not matching the `version` value.

What should we do about it? Removing it or requesting it to be equal to the version in the package?

**Comment by confused-Techie** [comment]
Honestly I feel it makes sense to just remove it, which should also happen on the PPM-end side.

But if others feel differently we could always use it to double check the version of the tag we are grabbing, but yeah doesn't make much sense to me to leave it around, when even Atom wasn't using it in any known way.

It does show up in the logs which is nice for identifying this endpoint, but doesn't do much else
