### ISSUE TITLE
Provide initial Open API 3.0 Definition

### ISSUE THREAD

**Issue by Spiker985** [pulsar-edit/package-backend#5]
Hand-Made Definition Available [here](https://gist.github.com/Spiker985/0d053e6bce765b201fadb5ba0a8c41a9) or the raw link is available [here](https://gist.githubusercontent.com/Spiker985/0d053e6bce765b201fadb5ba0a8c41a9/raw/0bba3af4051106711622e39b100840344cd5b869/openapi3_def.yaml). Note that this is a yaml file, however, it can also be json. Yaml was simply easier to write by hand.

Last updated 2022-12-11

- [ ] OAuth scopes need to match actual in-use scopes
- [ ] Authentication endpoint needs updated since it has now gone live

Ideally, this definition can be generated from the JSDocs eventually, and can live on a swagger.io instance on the front or backend site(s).

I recommend importing this into Postman to attempt to use it. Postman -> Ctrl + O -> File -> Downloaded file path OR Link -> Raw Link -> Show Import Settings -> Request/Response parameter generation -> Schema

**Comment by kyjus25** [comment]
> and can live on a swagger.io instance on the front or backend site(s).

Done in #16
