### ISSUE TITLE
Tracking Package Contacts - License

### ISSUE THREAD

**Issue by confused-Techie** [pulsar-edit/package-backend#57]
Alright, as anyone that's been around on our Discord knows, we recently had to consider the legal implications of redistributing packages, possibly against the license within the package.

This means we needed any one of the following to legal host our packages:
* Express Consent from the Package Author (This is done by uploading to the registry, or confirming we are allowed to host the package)
* A License that allows Redistribution

So to start this process I began looking through every unique license that was pulled from Atoms registry, this included 149 unique licenses types being defined throughout every package. This included many saying "License in License" and so on.

So with a lot of help from the rest of the Pulsar Team, we manually combed through every license, and studied the license itself to verify if redistribution was allowed.

Many packages we had to visit the repo itself to verify the license within the repo and confirm we were able to redistribute.

From there that still left many many packages who had no license specified, or a license of a type that does not exist.

For those following packages we then went ahead to the repo of each one, and opened an issue to confirm if we were allowed to redistribute their content.

Although many of the repos have since been archived (Many stating this was because the sunset of Atom), and many additionally may have had their "Issues" disabled for the repo. In either previous case we will go ahead and delete the package from our registry.

But for those that remain we were able to create Issues asking about this, of which many package authors have already responded. But for the ones that haven't I will go ahead and list them here, for ease of access and checking back in later.

The deadline for these remaining package authors to respond is 3 weeks. At which time the package will be removed. 

---

* [latex-online](https://github.com/Spijkervet/atom-latex-online/issues/2)
* [language-wex5](https://github.com/ranforce/language-wex5/issues/1)
* [hotdog-tabs](https://github.com/kmh11/hotdog-tabs/issues/3)
* [bemhtml](https://github.com/jchouse/bemhtml/issues/9)
* [github-user-datatip](https://github.com/jgebhardt/atom-github-user-datatip/issues/1)
* [atom-arma-language](https://github.com/DevZupa/Atom-Arma-Language/issues/4)
* [language-dm](https://github.com/stuicey/language-dm/issues/6)
* [egg](https://github.com/Cxeep/atom-egg/issues/1)
* [next-dark](https://github.com/casesandberg/next-dark-ui/issues/1)
* [language-multiverse](https://github.com/drewctaylor/language-multiverse/issues/1)
* [autoclose-editors](https://github.com/pvienneau/atom-clear-deleted-editors/issues/6)
* [scheme-syntax](https://github.com/rogerbutt/scheme-syntax/issues/2)
* [language-bgscript](https://github.com/gwillz/language-bgscript/issues/1)
* [quilt-completions](https://github.com/lemonmade/quilt-completions/issues/1)
* [atom-selenium-autocomplete](https://github.com/ibhubs/atom-selenium-autocomplete/issues/3)
* [atom-monokai-one-dark](https://github.com/AntonioDeCasper/atom-monokai-one-dark/issues/1)
* [linter-flexible-survival](https://github.com/hahaluckyme/linter-flexible-survival/issues/1)
* [single-ut](https://github.com/lawrencebla/single-ut-atom/issues/1)
* [language-tree-test](https://github.com/Aerijo/language-tree-test/issues/2)
* [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler/issues/426)
* [mura-snippets](https://github.com/rwatts3/atom-mura-snippets/issues/1)
* [haskell-tools](https://github.com/nboldi/haskell-tools-atom/issues/48)
* [language-todotxt-plus](https://github.com/LerBigDev/language-todotxt-plus/issues/2)
* [autocomplete-webgl](https://github.com/hughsk/autocomplete-webgl/issues/3)
* [emp-frontend-devtool](https://github.com/RYTong/emp-frontend-devtool/issues/28)
* [language-nagios](https://github.com/dkniffin/atom-nagios/issues/3)
* [language-t8-assembly](https://github.com/pjht/language-t8-assembly/issues/1)
* [language-topas](https://github.com/joostverburg/language-topas/issues/5)
* [itunes](https://github.com/reduxd/atom-itunes/issues/6)
* [execute-command](https://github.com/giraugh/execute-command/issues/2)
* [language-antimony](https://github.com/0u812/language-antimony/issues/1)
* [smilebin](https://github.com/tdenovan/smilebin-atom-package/issues/2)
* [sandstorm-syntax](https://github.com/devan-sisson/sandstorm-atom-syntax/issues/1)
* [swinsian](https://github.com/tgrrtt/atom-swinsian/issues/1)
* [language-maxlang](https://github.com/bascouch/language-maxlang/issues/1)
* [export-project-html](https://github.com/emendir/Export-Project-to-HTML---Atom-Plugin/issues/1)
* [language-spf](https://github.com/mgoodings/language-sqf/issues/6)
* [goproof](https://github.com/mitchr/goproof/issues/1)
* [find-dependencies](https://github.com/nikitabulatov/find-dependencies/issues/1)
* [aural-coding](https://github.com/probablycorey/aural-coding/issues/17)
* [language-epic](https://github.com/ucsc-mikey/language-epic-atom/issues/2)
* [neolao](https://github.com/neolao/atom-package-neolao/issues/1)
* [insert-require](https://github.com/vjeux/insert-require/issues/3)
* [mdfld](https://github.com/quackingduck-archive/mdfld/issues/5)
* [snippr-io-editors-atom](https://github.com/snippr-io/snippr-io-editors-atom/issues/1)
* [atom-grok-highlighter](https://github.com/nickStefanko/atom-grok-highlighter/issues/1)
* [atom-expressionengine](https://github.com/mindpixel-labs/atom-expressionengine/issues/3)
* [cga-4bit-syntax](https://github.com/DutChen18/cga-4bit/issues/1)
* [darker-one-dark-syntax](https://github.com/sentisso/darker-one-dark-syntax/issues/3)
* [language-cwl-atom](https://github.com/SolomonShorser-OICR/language-cwl-atom/issues/2)
* [language-structured-text](https://github.com/E-Renshaw/language-structured-text/issues/4)
* [atom-nonmem](https://github.com/dpastoor/atom-nonmem/issues/2)
* [hello-world](https://github.com/distalx/hello-world-atom/issues/1)
* [language-fhem](https://github.com/Fankserver/atom-language-fhem/issues/2)
* [cwl-solarized-dark](https://github.com/SolomonShorser-OICR/cwl-solarized-dark/issues/1)
* [thedaniel-test-package-2](https://github.com/thedaniel/test-package-2/issues/1)
* [kobble](https://github.com/kobble-git/kobble-package/issues/1)
* [irene-emojify](https://github.com/prymnumber/emojify/issues/1)
* [devfactory-language-client](https://github.com/Mizzlr/Atom-Language-Client/issues/1)
* [language-category-compiler](https://github.com/jack-willturner/language-category-compiler/issues/1)
* [language-gpp](https://github.com/Milys/language-gpp/issues/1)
* [language-tesp](https://github.com/aleixpinardell/language-tesp/issues/1)
* [continuum-atom](https://github.com/dualmoon/continuum-atom/issues/1)
* [cut-line](https://github.com/tekkub/cut-line/issues/28)
* [nitrogen](https://github.com/petejkim/nitrogen-dist/issues/47)
* [luser-inerface-ui](https://github.com/elifoster/luser-interface/issues/2)
* [made-of-code-atom](https://github.com/mkdynamic/made-of-code-atom/issues/3)
* [keystrokes](https://github.com/lilyszhang/keystrokes/issues/1)
* [language-jsil](https://github.com/tompntn/language-jsil/issues/1)
* [lang-gdscript](https://github.com/PrestonKnopp/language-gdscript/issues/54)
* [language-ivan](https://github.com/perficientautomation/atom-language-ivan/issues/2)
* [monokai-soft](https://github.com/nikteg/atom-monokai-soft/issues/3)
* [oblivion-contrast-syntax](https://github.com/Trigan2025/oblivion-contrast-syntax/issues/1)

**Comment by Digitalone1** [comment]
@confused-Techie To retain the names after the package deletion you would have to make `pointer` column of `names` table nullable (we set `NOT NULL` on creation).

In PostgreSQL the default action for foreign keys is `ON DELETE SET NULL`, so you can set the field nullable to change it to null when the package is deleted. This way the names of deleted packages will remain with null pointer.

**Comment by confused-Techie** [comment]
@Digitalone1 great news! Thanks, so if we just set names to be nullable, then the existing code should work just fine for not deleting it?

**Comment by Digitalone1** [comment]
> @Digitalone1 great news! Thanks, so if we just set names to be nullable, then the existing code should work just fine for not deleting it?

No, we should remove the query for names deletion. At the moment, if you need to remove a package, collect all queries in deletePackageByName and strip only the part related to the names table.

**Comment by confused-Techie** [comment]
> > @Digitalone1 great news! Thanks, so if we just set names to be nullable, then the existing code should work just fine for not deleting it?
> 
> No, we should remove the query for names deletion. At the moment, if you need to remove a package, collect all queries in deletePackageByName and strip only the part related to the names table.

Thanks for the info, we could handle this on a PR here soon, but sounds good to me

**Comment by Digitalone1** [comment]
> In PostgreSQL the default action for foreign keys is `ON DELETE SET NULL`, so you can set the field nullable to change it to null when the package is deleted. This way the names of deleted packages will remain with null pointer.

Unfortunately, I'm wrong. We have to drop the existing constraint and make a new one. In #62 there's an easy step by step guide to do this.

**Comment by confused-Techie** [comment]
Alright, it's been 3 weeks. Time to start going through this list and closing the issues, marking which packages should be removed.

**Comment by confused-Techie** [comment]
Alright, all issues here are closed and have responded to properly.

All that leaves is for the actual deletion to occur.

Some quick stats about the last step here.

Out of 105 packages marked as having invalid licenses, that is no `license` key in the `package.json` and no `LICENSE.md` within the repo:
* 21 Community Packages had responses from the maintainers to keep them
* 83 Packages either were archived after creating the issue, or received no response within 3 weeks and must be removed.
* 1 Atom Package was mistakenly marked 

So this means 83 packages will have to be removed from the Pulsar Package Registry. These packages will be added to our [Admin Actions](https://github.com/pulsar-edit/package-backend/blob/main/docs/reference/Admin_Actions.md) log, and hopefully in the future if someone wants, they can recreate the functionality within said package.
