### ISSUE TITLE
[BUG] Publish doesn't work for a renamed package

### ISSUE THREAD

**Issue by ndr-brt** [pulsar-edit/package-backend#63]
**Is this Bug Present in the upstream API Server?**
- [ ] Yes
- [ ] No
- [ ] Unsure

**What is the Bug**
The url of our plugin changed (from `atom-*` to `pulsar-*`) and the publication started to fail again.

**How to Replicate the Bug**
After login, running `pulsar -p publish patch` caused:
```
Preparing and tagging a new version ✓
Pushing v3.16.44 tag ✓
Publishing tidalcycles@v3.16.44 ✗
Creating new version failed: The package.json at owner/repo isn't valid
```

**Comment by confused-Techie** [comment]
Thanks a ton for the bug report, I really appreciate the information, and will look into this issue.

**Comment by ndr-brt** [comment]
If you need a retry please ping me on discord ;)

**Comment by confused-Techie** [comment]
> If you need a retry please ping me on discord ;)

I will absolutely let you know

**Comment by ndr-brt** [comment]
@confused-Techie there could be the possibility to delete the tidalcycles packages and upload it again? Would that work?
Because now the need to update it is becoming more and more necessary.

**Comment by confused-Techie** [comment]
> @confused-Techie there could be the possibility to delete the tidalcycles packages and upload it again? Would that work? Because now the need to update it is becoming more and more necessary.

You could do that, although the name `tidalcycles` would not be reusable by default.
We could try to make an exception and have manual intervention for the name to become available again, but if you'd like, we have merged all the changes with what I believe will fix this issue after #50 

Now I'm just trying to clean up a few things to give us more faith in that new system. But I can try to sprint these changes this weekend and get them pushed to prod. But let me know what you'd like to do and I'll work with you

**Comment by ndr-brt** [comment]
Great to hear that, I'll wait to see if the issue will be fixed by the next rollout :raised_hands:

**Comment by confused-Techie** [comment]
@ndr-brt If possible would you be willing to give this another try?

We now have success with users publishing new package versions.

Keep in mind the new pinned issue on this repo. As in if it says you successfully published the new version, keep in mind the website and Pulsar might not show it, but using the API you'll be able to see the new version, or if you have the package installed you'll be prompted for the upgrade to your newer version.

Otherwise using `ppm upgrade --list` will show the newer update

**Comment by ndr-brt** [comment]
@confused-Techie it worked! no errors :partying_face:  thanks a lot. I will close the issue
